apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rabbitmq
  description: Deploys the rabbit mq service
spec:
  replicas: 1
  selector:
    name: rabbitmq
  triggers:
    - 
      type: ConfigChange
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
       - 
         name: rabbitmq
         image: 172.30.200.195:5000/dbs/rabbitmq:latest
         ports:
         - name: mq1
           containerPort: 4369 
           protocol: TCP
         - name: mq2
           containerPort: 5671 
           protocol: TCP
         - name: mq3
           containerPort: 5672
           protocol: TCP
         - name: mq4
           containerPort: 25672
           protocol: TCP

