apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: rabbitmq
      description: Deploys the rabbit mq service
    spec:
      replicas: 1
      selector:
        name: rabbitmq
      triggers:
        - 
          type: ConfigChange
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: rabbitmq
        spec:
          containers:
           - 
             name: rabbitmq
             image: 172.30.200.195:5000/dbs/rabbitmq:latest
             ports:
             - name: mq1
               containerPort: 4369 
               protocol: TCP
             - name: mq2
               containerPort: 5671 
               protocol: TCP
             - name: mq3
               containerPort: 5672
               protocol: TCP
             - name: mq4
               containerPort: 25672
           protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq-service
      annotations:
        description: Exposes and load balances the mq services
    spec:
      ports:
        - name: mq1
          port: 4369
          targetPort: 4369
        - name: mq2
          port: 5671
          targetPort: 5671
        - name: mq3
          port: 5672
          targetPort: 5672
        - name: mq4
          port: 25672
          targetPort: 25672
      selector:
        name: rabbitmq